apiVersion: v1
description: ELK(Elasticsearch + Logstash + Kibana)
name: elk
maintainers:
- name: zzh
  email: zhangzh3@asp.citic.com
version: 6.5.4
icon: elk.png
sources:
- https://www.elastic.co/products/elasticsearch
- https://www.elastic.co/products/kibana
- https://www.elastic.co/products/logstash