dependencies:
  - name: kibana
    version: 6.5.4
    condition: kibana.enabled
  - name: logstsh
    version: 6.5.4
    condition: logstash.enabled
  - name: elasticsearch
    version: 6.5.4
    condition: elasticsearch.enabled